import { computeLeadScore, derivePriorityBand, suggestNextAction } from "./automation";
import type { Lead, LeadActivity, LeadStatus, SourcePlatform } from "./types";

function isoDaysAgo(days: number, hour = 10) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

function isoDaysFromNow(days: number, hour = 11) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

const repColorByName: Record<string, string> = {
  "Alex Morgan": "bg-violet-500",
  "Sarah Chen": "bg-blue-500",
  "Marcus Johnson": "bg-emerald-500",
  "Lisa Park": "bg-amber-500",
  "David Torres": "bg-rose-500",
};

function repInitials(name: string) {
  return name
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
}

interface SeedLeadInput {
  id: string;
  name: string;
  email: string;
  phone: string;
  vehicle: string;
  category: string;
  budget: number;
  status: LeadStatus;
  source: SourcePlatform;
  assignedTo: string;
  createdDaysAgo: number;
  lastActivityDaysAgo: number;
  tradeIn: boolean;
  financing: boolean;
  followUpInDays: number | null;
  note: string;
}

const seedInput: SeedLeadInput[] = [
  {
    id: "L001",
    name: "James Richardson",
    email: "james.r@email.com",
    phone: "(555) 234-5678",
    vehicle: "2024 Toyota Camry SE",
    category: "Sedan",
    budget: 32000,
    status: "new",
    source: "Website",
    assignedTo: "Alex Morgan",
    createdDaysAgo: 1,
    lastActivityDaysAgo: 1,
    tradeIn: false,
    financing: true,
    followUpInDays: 0,
    note: "Fuel-efficient sedan for daily commute. Pre-approved up to $35k.",
  },
  {
    id: "L002",
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "(555) 345-6789",
    vehicle: "2024 Ford F-150 XLT",
    category: "Truck",
    budget: 52000,
    status: "contacted",
    source: "Offline Event",
    assignedTo: "Marcus Johnson",
    createdDaysAgo: 2,
    lastActivityDaysAgo: 1,
    tradeIn: true,
    financing: false,
    followUpInDays: 1,
    note: "Needs towing package and evaluating trade-in value.",
  },
  {
    id: "L003",
    name: "David Chen",
    email: "david.chen@email.com",
    phone: "(555) 456-7890",
    vehicle: "Tesla Model 3 Long Range",
    category: "EV",
    budget: 48000,
    status: "qualified",
    source: "Google",
    assignedTo: "Sarah Chen",
    createdDaysAgo: 4,
    lastActivityDaysAgo: 2,
    tradeIn: false,
    financing: true,
    followUpInDays: 2,
    note: "Very motivated buyer. Ready to purchase this week.",
  },
  {
    id: "L004",
    name: "Amanda Foster",
    email: "amanda.f@email.com",
    phone: "(555) 567-8901",
    vehicle: "2024 BMW 3 Series 330i",
    category: "Luxury",
    budget: 65000,
    status: "test_drive",
    source: "Facebook",
    assignedTo: "Lisa Park",
    createdDaysAgo: 6,
    lastActivityDaysAgo: 1,
    tradeIn: false,
    financing: false,
    followUpInDays: 1,
    note: "Test drive complete; comparing M Sport package options.",
  },
  {
    id: "L005",
    name: "Robert Hayes",
    email: "rob.hayes@email.com",
    phone: "(555) 678-9012",
    vehicle: "2024 Chevrolet Silverado LTZ",
    category: "Truck",
    budget: 58000,
    status: "negotiating",
    source: "Google",
    assignedTo: "David Torres",
    createdDaysAgo: 10,
    lastActivityDaysAgo: 2,
    tradeIn: true,
    financing: false,
    followUpInDays: -1,
    note: "Negotiating on MSRP discount and accessory bundle.",
  },
  {
    id: "L006",
    name: "Jennifer Wu",
    email: "jen.wu@email.com",
    phone: "(555) 789-0123",
    vehicle: "2024 Mercedes-Benz C300",
    category: "Luxury",
    budget: 72000,
    status: "won",
    source: "Offline Event",
    assignedTo: "Alex Morgan",
    createdDaysAgo: 14,
    lastActivityDaysAgo: 6,
    tradeIn: true,
    financing: true,
    followUpInDays: null,
    note: "Deal closed successfully with dealership financing.",
  },
  {
    id: "L007",
    name: "Michael Torres",
    email: "m.torres@email.com",
    phone: "(555) 890-1234",
    vehicle: "2024 Jeep Grand Cherokee L",
    category: "SUV",
    budget: 55000,
    status: "not_interested",
    source: "Twitter",
    assignedTo: "Marcus Johnson",
    createdDaysAgo: 16,
    lastActivityDaysAgo: 8,
    tradeIn: true,
    financing: true,
    followUpInDays: null,
    note: "Chose another dealership with a better trade-in offer.",
  },
  {
    id: "L008",
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "(555) 901-2345",
    vehicle: "2024 Honda CR-V Hybrid",
    category: "SUV",
    budget: 39000,
    status: "new",
    source: "Website",
    assignedTo: "Sarah Chen",
    createdDaysAgo: 1,
    lastActivityDaysAgo: 1,
    tradeIn: false,
    financing: true,
    followUpInDays: 1,
    note: "First-time buyer comparing hybrid models.",
  },
  {
    id: "L009",
    name: "Christopher Lee",
    email: "chris.lee@email.com",
    phone: "(555) 012-3456",
    vehicle: "2024 Hyundai Tucson SEL",
    category: "SUV",
    budget: 36000,
    status: "contacted",
    source: "Twitter",
    assignedTo: "Lisa Park",
    createdDaysAgo: 3,
    lastActivityDaysAgo: 2,
    tradeIn: false,
    financing: true,
    followUpInDays: 0,
    note: "Family buyer, looking for AWD and third-row options.",
  },
  {
    id: "L010",
    name: "Patricia Johnson",
    email: "pat.j@email.com",
    phone: "(555) 123-4567",
    vehicle: "2024 Kia Telluride EX",
    category: "SUV",
    budget: 47000,
    status: "qualified",
    source: "Offline Event",
    assignedTo: "David Torres",
    createdDaysAgo: 5,
    lastActivityDaysAgo: 1,
    tradeIn: true,
    financing: true,
    followUpInDays: 2,
    note: "Spouse approval pending. Strong intent.",
  },
  {
    id: "L011",
    name: "William Anderson",
    email: "will.a@email.com",
    phone: "(555) 234-5670",
    vehicle: "2024 Audi Q5 Premium Plus",
    category: "Luxury",
    budget: 62000,
    status: "test_drive",
    source: "Facebook",
    assignedTo: "Alex Morgan",
    createdDaysAgo: 7,
    lastActivityDaysAgo: 1,
    tradeIn: false,
    financing: false,
    followUpInDays: 0,
    note: "Test drive positive; comparing with Mercedes GLC.",
  },
  {
    id: "L012",
    name: "Karen Martinez",
    email: "karen.m@email.com",
    phone: "(555) 345-6780",
    vehicle: "2024 Toyota RAV4 Prime",
    category: "SUV",
    budget: 44000,
    status: "negotiating",
    source: "Google",
    assignedTo: "Marcus Johnson",
    createdDaysAgo: 11,
    lastActivityDaysAgo: 3,
    tradeIn: false,
    financing: true,
    followUpInDays: -2,
    note: "Negotiating accessories package and paint protection.",
  },
  {
    id: "L013",
    name: "Thomas Brown",
    email: "thomas.b@email.com",
    phone: "(555) 456-7891",
    vehicle: "2024 Porsche Cayenne",
    category: "Luxury",
    budget: 95000,
    status: "won",
    source: "Offline Event",
    assignedTo: "Sarah Chen",
    createdDaysAgo: 18,
    lastActivityDaysAgo: 9,
    tradeIn: true,
    financing: false,
    followUpInDays: null,
    note: "Purchased Cayenne S with Premium Plus package.",
  },
  {
    id: "L014",
    name: "Lisa Thompson",
    email: "lisa.t@email.com",
    phone: "(555) 567-8902",
    vehicle: "2024 Volkswagen Tiguan SE",
    category: "SUV",
    budget: 35000,
    status: "not_interested",
    source: "Twitter",
    assignedTo: "Lisa Park",
    createdDaysAgo: 19,
    lastActivityDaysAgo: 10,
    tradeIn: false,
    financing: true,
    followUpInDays: null,
    note: "Budget constraints; delayed purchase decision.",
  },
  {
    id: "L015",
    name: "Mark Davis",
    email: "mark.d@email.com",
    phone: "(555) 678-9013",
    vehicle: "2024 Dodge Challenger R/T",
    category: "Sport",
    budget: 42000,
    status: "new",
    source: "Website",
    assignedTo: "David Torres",
    createdDaysAgo: 1,
    lastActivityDaysAgo: 1,
    tradeIn: false,
    financing: true,
    followUpInDays: 1,
    note: "Wants Scat Pack trim if financing permits.",
  },
  {
    id: "L016",
    name: "Nancy Wilson",
    email: "nancy.w@email.com",
    phone: "(555) 789-0124",
    vehicle: "2024 Subaru Outback Limited",
    category: "SUV",
    budget: 40000,
    status: "contacted",
    source: "Google",
    assignedTo: "Alex Morgan",
    createdDaysAgo: 3,
    lastActivityDaysAgo: 1,
    tradeIn: true,
    financing: true,
    followUpInDays: 1,
    note: "Moving to Colorado; AWD is mandatory.",
  },
  {
    id: "L017",
    name: "Steven Clark",
    email: "s.clark@email.com",
    phone: "(555) 890-1235",
    vehicle: "2024 Genesis GV70 Advanced",
    category: "Luxury",
    budget: 58000,
    status: "qualified",
    source: "Google",
    assignedTo: "Sarah Chen",
    createdDaysAgo: 6,
    lastActivityDaysAgo: 2,
    tradeIn: true,
    financing: false,
    followUpInDays: 2,
    note: "Comparing GV70 against Acura MDX.",
  },
  {
    id: "L018",
    name: "Angela White",
    email: "angela.w@email.com",
    phone: "(555) 901-2346",
    vehicle: "2024 Mazda CX-5 Carbon Edition",
    category: "SUV",
    budget: 38000,
    status: "new",
    source: "Offline Event",
    assignedTo: "Marcus Johnson",
    createdDaysAgo: 1,
    lastActivityDaysAgo: 1,
    tradeIn: false,
    financing: true,
    followUpInDays: 1,
    note: "Visited booth with spouse, interested in Carbon Edition.",
  },
  {
    id: "L019",
    name: "Daniel Harris",
    email: "d.harris@email.com",
    phone: "(555) 012-3457",
    vehicle: "2024 Rivian R1T Adventure",
    category: "EV",
    budget: 75000,
    status: "negotiating",
    source: "Facebook",
    assignedTo: "Lisa Park",
    createdDaysAgo: 9,
    lastActivityDaysAgo: 3,
    tradeIn: false,
    financing: true,
    followUpInDays: 0,
    note: "Comparing delivery timelines against competitor offers.",
  },
  {
    id: "L020",
    name: "Michelle Turner",
    email: "m.turner@email.com",
    phone: "(555) 123-4568",
    vehicle: "2024 Cadillac Escalade Premium Luxury",
    category: "Luxury",
    budget: 105000,
    status: "won",
    source: "Google",
    assignedTo: "David Torres",
    createdDaysAgo: 15,
    lastActivityDaysAgo: 8,
    tradeIn: true,
    financing: false,
    followUpInDays: null,
    note: "Purchased with Platinum upgrade.",
  },
];

export const seedLeads: Lead[] = seedInput.map((item) => {
  const createdAt = isoDaysAgo(item.createdDaysAgo, 10);
  const lastActivityAt = isoDaysAgo(item.lastActivityDaysAgo, 14);
  const followUpAt = item.followUpInDays === null ? null : isoDaysFromNow(item.followUpInDays, 16);

  const base = {
    id: item.id,
    name: item.name,
    email: item.email,
    phone: item.phone,
    vehicle_interest: item.vehicle,
    vehicle_category: item.category,
    budget: item.budget,
    status: item.status,
    source_platform: item.source,
    assigned_to: item.assignedTo,
    assigned_initials: repInitials(item.assignedTo),
    assigned_color: repColorByName[item.assignedTo] ?? "bg-gray-500",
    created_at: createdAt,
    last_activity_at: lastActivityAt,
    follow_up_at: followUpAt,
    financing: item.financing,
    trade_in: item.tradeIn,
    notes: [item.note],
    updated_by: "System",
  };

  const score = computeLeadScore({
    status: base.status,
    source_platform: base.source_platform,
    budget: base.budget,
    trade_in: base.trade_in,
    financing: base.financing,
    last_activity_at: base.last_activity_at,
    follow_up_at: base.follow_up_at,
  });

  const priority = derivePriorityBand(score);
  const nextAction = suggestNextAction({ status: base.status, follow_up_at: base.follow_up_at });

  return {
    ...base,
    score,
    priority_band: priority,
    next_action: nextAction,
  };
});

export const seedActivities: LeadActivity[] = [
  {
    id: crypto.randomUUID(),
    lead_id: "L012",
    type: "call",
    description: "Completed follow-up call and discussed accessories package.",
    lead_name: "Karen Martinez",
    user: "Marcus Johnson",
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: crypto.randomUUID(),
    lead_id: "L004",
    type: "test_drive",
    description: "Test drive completed successfully with positive sentiment.",
    lead_name: "Amanda Foster",
    user: "Lisa Park",
    created_at: new Date(Date.now() - 64 * 60000).toISOString(),
  },
  {
    id: crypto.randomUUID(),
    lead_id: "L003",
    type: "status",
    description: "Status moved from Contacted to Qualified.",
    lead_name: "David Chen",
    user: "Sarah Chen",
    created_at: new Date(Date.now() - 91 * 60000).toISOString(),
  },
  {
    id: crypto.randomUUID(),
    lead_id: "L001",
    type: "email",
    description: "Sent personalized brochure and pricing summary.",
    lead_name: "James Richardson",
    user: "Alex Morgan",
    created_at: new Date(Date.now() - 125 * 60000).toISOString(),
  },
  {
    id: crypto.randomUUID(),
    lead_id: "L018",
    type: "created",
    description: "New lead created from Offline Event booth scan.",
    lead_name: "Angela White",
    user: "System",
    created_at: new Date(Date.now() - 160 * 60000).toISOString(),
  },
  {
    id: crypto.randomUUID(),
    lead_id: "L019",
    type: "meeting",
    description: "Follow-up meeting scheduled for tomorrow.",
    lead_name: "Daniel Harris",
    user: "Lisa Park",
    created_at: new Date(Date.now() - 210 * 60000).toISOString(),
  },
];
